# MASKOCSORT, OCSORT, DEEPOCSORT, DEEPSORT
tracker : MASKOCSORT
# MaskRCNN SOLOv2 YOLOv7
predictor : SOLOv2
# AKAZE_BF AKAZE_FLANN BRISK_BF BRISK_FLANN ORB_BF ORB_FLANN COSINESL
matcher :
# configs/SOLOv2/SOLOv2_R50_FPN_3x.yaml configs/MaskRCNN/MaskRCNN_R50_FPN_3x.yaml configs/YOLOv7_Mask.yaml
config_file : configs/SOLOv2/SOLOv2_R50_FPN_3x.yaml
# checkpoints/SOLOv2_R50_3x.pth checkpoints/MaskRCNN_R50_3x.pkl checkpoints/YOLOv7_Mask.pt
weight_file : checkpoints/SOLOv2_R50_3x.pth
is_save_result : True
frame_use : 3
video_path : # /home/catchall/Videos/D01_202306082023014945_006.mp4 # D01_202306082023014945_006 D01_20230514220419_003, D01_20230514075152_004, ch01_20181213073211_008, ch01_20181213054208_009
image_path :  /home/catchall/Documents/thesis/enhance/data/D01_202306082023014945_006/pce
output_dir :  /home/catchall/Documents/thesis/enhance/data/D01_202306082023014945_006/track_pce
# {0: person, 1: bicycle, 2: car, 3: motorcycle, 4: airplane, 5: bus, 6: train, 7: truck}
class_list : [1,2,3,5,7]
roi:
# roi : [[335, 52, 592, 170], [0, 296, 224, 417], [690, 116, 960, 211]]  # UAD
# roi : [[1126, 0, 1918, 200]]  # 1 APMC
# roi : [883.99, 1.65, 1918.08, 241.23] #2
confidence_threshold : 0.5
iop_threshold : 0.1
track_thresh : 0.3
iou_thresh : 0.3
_aspect_ratio_thresh : 1.6
_min_box_area_thresh : 10
iou_weight : 0.3
vd_weight : 0.2
min_hits : 3
max_age : 30
