use_maskocsort : True
# MaskRCNN YOLOv7
predictor : YOLOv7
# configs/MaskRCNN/MaskRCNN_R50_FPN_3x.yaml configs/YOLOv7_Mask.yaml
config_file : configs/YOLOv7_Mask.yaml
# checkpoints/MaskRCNN_R50_3x.pkl checkpoints/YOLOv7_Mask.pt
weight_file : checkpoints/YOLOv7_Mask.pt
is_save_result : True
frame_use : 1
video_path : data/ch01_20230605160142_01.mp4
image_path :  # data/images/
image_fps : # fps if source is images
output_dir :  data/ch01_20230605160142_01
# {0: person, 1: bicycle, 2: car, 3: motorcycle, 4: airplane, 5: bus, 6: train, 7: truck}
class_list : [1]
roi:
# roi : [[1126, 0, 1918, 200]]  # 1 APMC
confidence_threshold : 0.5
iop_threshold : 0.1
track_thresh : 0.3
iou_thresh : 0.3
_aspect_ratio_thresh : 1.6
_min_box_area_thresh : 10
iou_weight : 0.3
vd_weight : 0.2
min_hits : 3
max_age : 30
